### ISSUE TITLE
Cycle in Greek alphabet diverges to Roman numerals on "xi" 

### ISSUE THREAD

**Issue by victorkristof** [Konfekt/vim-CtrlXA#11]
Hey there,

Really nice plugin :)

I was just cycling through the Greek alphabet with `C-X` and this happened:
```
mu -> nu -> xi -> xii -> xiii
```
which is kind of funny but unfortunate because it (correctly) diverged from the Greek alphabet to the Roman numerals.
Yet, this is not what I was expecting - I wanted to get `omikron` after `xi`!

Thanks!

**Comment by Konfekt** [comment]
Hey, there was a similar problem intertwining of Latin letters and Latin numerals. That's where the comment after the default configuration comes from:

> If you prefer the letters i, v and I, V to run through the Latin alphabet instead of the Roman numerals, move these letters from the last pair of arrays two the penultimate one. 

By default, Roman numerals do not go further than `ix`; to avoid

-  incrementing to `x` and then successively the Latin letters instead of Roman numerals (and vice-versa), but, as you now pointed out,
- incrementing to `xi` and then successively Greek letters instead of Roman numerals (and vice-versa).

You probably have added Roman numerals beyond `ix`?

**Comment by victorkristof** [comment]
> You probably have added Roman numerals beyond ix?

Nope... and that's when I realized it's `vim-speeddating` that's interfering: https://github.com/tpope/vim-speeddating/blob/master/autoload/speeddating.vim#L256

Roman numerals are handled by `vim-speeddating`, hence the divergence, which is not due to a bug in yours...

Any idea I could have the best of both plugins?

**Comment by Konfekt** [comment]
As long as speed-dating falls back to CtrlXA, speed-dating takes command of Roman numerals:

> It can also increment roman numerals ...

The other way around, falling back to speed-dating is inefficient. Best would be an option in speed-dating to disable roman numerals.

**Comment by victorkristof** [comment]
Got it, thanks!
